# =============================================================================
# БАЗОВЫЕ НАСТРОЙКИ HUGO
# =============================================================================

baseURL = "https://devopsway.ru"
languageCode = "ru"
defaultContentLanguage = "ru"
title = "DevOps Way - Практические гайды"
theme = "PaperMod"

# Google Analytics
googleAnalytics = "G-B9KCE8TFRB"

# SEO и производительность
enableRobotsTXT = true
canonifyURLs = true
enableEmoji = true

# Сборка
buildDrafts = false
buildFuture = false
buildExpired = false

# =============================================================================
# PAGINATION (новый синтаксис Hugo v0.128+)
# =============================================================================

[pagination]
pagerSize = 10
path = "page"

# =============================================================================
# МИНИФИКАЦИЯ И ОПТИМИЗАЦИЯ
# =============================================================================

[minify]
disableXML = true
minifyOutput = true

[minify.tdewolff.html]
keepDefaultAttrVals = false
keepDocumentTags = true
keepEndTags = true
keepQuotes = false
keepWhitespace = false

[minify.tdewolff.css]
precision = 1
keepCSS2 = true

[minify.tdewolff.js]
precision = 1
keepVarNames = false

# =============================================================================
# OUTPUTS И ФОРМАТЫ
# =============================================================================

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[outputFormats.JSON]
mediatype = "application/json"
baseName = "index"

# =============================================================================
# SITEMAP НАСТРОЙКИ
# =============================================================================

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

# =============================================================================
# MARKUP И SYNTAX HIGHLIGHTING + MERMAID
# =============================================================================

[markup]
[markup.highlight]
style = "github-dark"
lineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNumbersInTable = false
noClasses = true
tabWidth = 4

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
hardWraps = false

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

# =============================================================================
# TAXONOMIES
# =============================================================================

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# =============================================================================
# ПАРАМЕТРЫ ТЕМЫ PAPERMOD
# =============================================================================

[params]
# Окружение
env = "production"

# Основная информация
title = "DevOps Way"
description = "DevOps Way - практические гайды по автоматизации, CI/CD, мониторингу и управлению инфраструктурой. Пошаговые инструкции для DevOps инженеров всех уровней."
keywords = ["DevOps", "Docker", "Kubernetes", "CI/CD", "Monitoring", "Automation", "Infrastructure", "Git", "SSH", "Ansible", "Terraform", "Jenkins", "GitHub Actions", "Prometheus", "Grafana"]
author = "DevOps Way"
images = ["/images/devopsway-og.png"]

# Дата и время
DateFormat = "2 January 2006"
defaultTheme = "auto"
disableThemeToggle = false

# Функциональность
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
ShowToc = true
TocOpen = false
ShowLastMod = false
ShowFullTextinRSS = true

# Поиск
fuseOpts = true

# Комментарии и социальное
comments = true
disableShare = false
disableSpecial1stPost = false
disableScrollToTop = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

# Навигация
UseHugoToc = true
disableAnchoredHeadings = false

# MERMAID ПОДДЕРЖКА
mermaid = true

# =============================================================================
# ГЛАВНАЯ СТРАНИЦА
# =============================================================================

[params.homeInfoParams]
Title = "🚀 DevOps Way - Практические гайды"
Content = """
**Практические DevOps инструкции, которые реально работают в production!**

🎯 **Аудитория:** DevOps инженеры всех уровней  
📚 **Формат:** пошаговые гайды + troubleshooting  
⚡ **Фокус:** практика над теорией, проверенные решения

**📂 Основные категории:**
- 🔧 **DevOps Essentials** - основы для новичков
- 🔒 **Security** - безопасность инфраструктуры  
- ⚡ **Automation** - автоматизация процессов
- 📊 **Monitoring** - мониторинг и алертинг
- 🚀 **CI/CD** - пайплайны и деплоймент

💡 **Почему DevOps Way:**
- Все инструкции тестируются в реальных условиях
- Никакой воды - только практические решения
- Troubleshooting типичных проблем
- Copy-paste команды для быстрого старта

👉 [Подписывайтесь на Telegram](https://t.me/devitway) для уведомлений о новых постах!
"""

# =============================================================================
# СОЦИАЛЬНЫЕ СЕТИ
# =============================================================================

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/devitway"

[[params.socialIcons]]
name = "github"
url = "https://github.com/devitway"

[[params.socialIcons]]
name = "rss"
url = "/feed.xml"

# =============================================================================
# КОММЕНТАРИИ GISCUS (настроить позже)
# =============================================================================

[params.giscus]
repo = "devitway/devopsway-blog"
repoId = "YOUR_REPO_ID"  # Получить с giscus.app после настройки Discussions
category = "Comments"
categoryId = "YOUR_CATEGORY_ID"  # Получить с giscus.app
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "preferred_color_scheme"
lang = "ru"
crossorigin = "anonymous"

# =============================================================================
# ASSETS И МЕДИА
# =============================================================================

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
safari_pinned_tab = "/safari-pinned-tab.svg"
disableHLJS = false
disableFingerprinting = false

# =============================================================================
# РЕДАКТИРОВАНИЕ ПОСТОВ
# =============================================================================

[params.editPost]
URL = "https://github.com/devitway/devopsway-blog/tree/main/content"
Text = "📝 Предложить изменения"
appendFilePath = true

# =============================================================================
# НАВИГАЦИОННОЕ МЕНЮ
# =============================================================================

[menu]
[[menu.main]]
identifier = "posts"
name = "📚 Все посты"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "🏷️ Категории"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "search"
name = "🔍 Поиск"
url = "/search/"
weight = 25

[[menu.main]]
identifier = "about"
name = "👨‍💻 О проекте"
url = "/about/"
weight = 30

[[menu.main]]
identifier = "telegram"
name = "💬 Telegram"
url = "https://t.me/devitway"
weight = 40

# =============================================================================
# RELATED CONTENT
# =============================================================================

[related]
includeNewer = true
threshold = 80
toLower = false

[[related.indices]]
name = "keywords"
weight = 100

[[related.indices]]
name = "tags"
weight = 80

[[related.indices]]
name = "categories"
weight = 60

[[related.indices]]
name = "date"
weight = 10

# =============================================================================
# PRIVACY НАСТРОЙКИ (GDPR) - исправлено для Hugo v0.141+
# =============================================================================

[privacy]
[privacy.disqus]
disable = true

[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = true
useSessionStorage = false

[privacy.instagram]
disable = true
simple = true

[privacy.x]
disable = false
enableDNT = true
simple = true

[privacy.vimeo]
disable = true
enableDNT = true
simple = true

[privacy.youtube]
disable = false
privacyEnhanced = true

# =============================================================================
# БЕЗОПАСНОСТЬ (исправлено для совместимости)
# =============================================================================

[security]
[security.exec]
allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^git$']
osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']

[security.funcs]
getenv = ['^HUGO_', '^CI$']

[security.http]
methods = ['(?i)GET|POST']
urls = ['.*']

# =============================================================================
# FRONTMATTER ФОРМАТЫ
# =============================================================================

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

# =============================================================================
# ДОПОЛНИТЕЛЬНЫЕ ЯЗЫКИ (для будущего развития)
# =============================================================================

[languages]
[languages.ru]
languageName = "Русский"
weight = 1
title = "DevOps Way - Практические гайды"

# Будущее развитие - английская версия
# [languages.en]
# languageName = "English"
# weight = 2
# title = "DevOps Way - Practical Guides"