baseURL = "https://devitway.github.io/devopsway-blog"
languageCode = "ru"
title = "DevOps Way - Практические гайды"
googleAnalytics = "G-B9KCE8TFRB"
theme = "PaperMod"

[params]
env = "production"
title = "DevOps Way"
description = "Практические DevOps гайды"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true
ShowRssButtonInSectionTermList = true
ShowFullTextinRSS = true

[params.homeInfoParams]
Title = "🚀 Добро пожаловать в DevOps Way!"
Content = """
Практические гайды по DevOps, которые работают в реальных проектах.

📚 **Категории:**
- 🔧 DevOps Essentials - основы для начинающих
- 🔒 Security - безопасность инфраструктуры  
- ⚡ Automation - автоматизация процессов
- 📊 Monitoring - мониторинг и алертинг
- 🚀 CI/CD - пайплайны и деплоймент
"""

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/devitway"

[menu]
[[menu.main]]
identifier = "posts"
name = "📚 Все посты"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "🏷️ Категории"
url = "/categories/"
weight = 20

[taxonomies]
category = "categories"
tag = "tags"

[markup]
[markup.highlight]
style = "github-dark"
lineNos = false
codeFences = true
guessSyntax = true

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]
